
sudo: required

services:
  - docker

language: bash

script:
  # build amd64 image
  - docker build -t cwmr/aws-cli:amd64 .
  # build armhf image
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t cwmr/aws-cli:arm -f Docekrfile.armhf .
  # push image
- >
  - wget -O manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64
  - chmod +x ./manifest-tool
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker push cwmr/aws-cli:amd64
      docker push cwmr/aws-cli:arm
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template cwmr/aws-cli:ARCH --target cwmr/aws-cli:latest
      TAG=$(grep "ENV AWS_CLI_VERSION" Dockerfile | awk 'NF>1{print $NF}')
      docker tag cwmr/gomp:amd64 cwmr/gomp:$TAG-amd64
      docker tag cwmr/gomp:arm cwmr/gomp:$TAG-arm
      docker push cwmr/gomp:$TAG-amd64
      docker push cwmr/gomp:$TAG-arm
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template cwmr/gomp:$TAG-ARCH --target cwmr/gomp:$TAG
    fi
